name: Pentest with Docker

on:
  workflow_dispatch:

jobs:
  pentest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Setup python # ワークフローのセクションごとに設定する名前。特に設定する必要はないが、どこでエラーが起きているかを把握する為にも設定しておいた方が良い。
        uses: actions/setup-python@v5 # Pythonのセットアップ
        with:
          python-version: "3.12" # Pythonのバージョン指定
      
      - name: Install Python dependencies
        working-directory: ./tginet_C18
        run: |
          pip install django
          python3 manage.py runserver &  # サーバーをバックグラウンドで起動
          # サーバーが立ち上がるまで待機
          until curl -s http://127.0.0.1:8000/ > /dev/null; do
            echo "Waiting for Django server to be up..."
            sleep 5
          done
          echo "Django server is up and running."

      - name: Run Kali Linux Docker Container
        run: |
          ls -l password.txt
          docker run --rm --privileged --network host -e DEBIAN_FRONTEND=noninteractive -v password.txt:/root/password.txt -v ${{ runner.temp }}/output:${{ runner.temp }}/output am2501/kalidef /bin/bash -c '
          hydra -l emfood -P root/password.txt 127.0.0.1 http-post-form "/admin/login:username=^USER^&password=^PASS^:F=スタッフアカウントの正しいユーザー名とパスワードを入力してください。どちらのフィールドも大文字と小文字は区別されます。" -s 8000 -o ${{ runner.temp }}/output/passwords.txt
          '
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability_report
          path: ${{ runner.temp }}/output/*
