name: Django CI

on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install Django
      - name: List files
        run: ls -R
      - name: Run migrations
        run: |
          cd ./Tginet_C18
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test

      - name: Run Django server
        run: |
          python manage.py runserver 0.0.0.0:8000 &
          until curl -s http://127.0.0.1:8000 > /dev/null; do
            echo "Waiting for Django server to be up..."
            sleep 5
          done
