name: Pentest with Docker

on:
  push:
    branches:
      - main
      - test

jobs:
  pentest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Setup python # ワークフローのセクションごとに設定する名前。特に設定する必要はないが、どこでエラーが起きているかを把握する為にも設定しておいた方が良い。
        uses: actions/setup-python@v2 # Pythonのセットアップ
        with:
          python-version: "3.12" # Pythonのバージョン指定
      
      - name: Install Python dependencies
        working-directory: ./tginet_C18
        run: |
          pip install django
          python3 /home/runner/work/project_C18/tginet_C18/tginet_C18/manage.py runserver 0.0.0.0:8000 &

      - name: Run Kali Linux Docker Container
        run: |
          docker run --rm --privileged --network host -e DEBIAN_FRONTEND=noninteractive kalilinux/kali-rolling /bin/bash -c "
          apt update && \
          apt install -y kali-linux-default && \
        #  nmap -sV -T4 127.0.0.1:8000"
